"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CenterColumn = exports.Row = exports.RoomsScroll = exports.Column = exports.NavStyled = exports.ImageStyled = exports.CenterContainer = exports.Exit = exports.SubHeader = exports.Header = exports.Input = exports.Label = exports.Form = exports.ButtonLink = exports.Button = exports.Block = exports.Container = void 0;
var styled_components_1 = require("styled-components");
var react_router_dom_1 = require("react-router-dom");
var buttonStyles_tsx_1 = require("../styles/buttonStyles.tsx");
var centerStyles = (0, styled_components_1.css)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  justify-content: center;\n  align-items: center;\n"], ["\n  display: flex;\n  justify-content: center;\n  align-items: center;\n"])));
exports.Container = styled_components_1.default.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  width: 100%;\n  display: flex;\n  padding: 8px;\n  flex-direction: column;\n  height: 100%;\n"], ["\n  width: 100%;\n  display: flex;\n  padding: 8px;\n  flex-direction: column;\n  height: 100%;\n"])));
exports.Block = styled_components_1.default.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: row;\n"], ["\n  display: flex;\n  flex-direction: row;\n"])));
exports.Button = styled_components_1.default.button(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  ", "\n"], ["\n  ", "\n"])), buttonStyles_tsx_1.ButtonStyles);
exports.ButtonLink = (0, styled_components_1.default)(react_router_dom_1.Link)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  text-decoration: none;\n  ", ";\n"], ["\n  text-decoration: none;\n  ", ";\n"])), buttonStyles_tsx_1.ButtonStyles);
exports.Form = styled_components_1.default.form(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  gap: 16px;\n  margin-top: auto;\n  height: 100%;\n  justify-content: end;\n"], ["\n  display: flex;\n  flex-direction: column;\n  gap: 16px;\n  margin-top: auto;\n  height: 100%;\n  justify-content: end;\n"])));
exports.Label = styled_components_1.default.label(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  margin-left: 8px;\n  font-size: 16px;\n"], ["\n  margin-left: 8px;\n  font-size: 16px;\n"])));
exports.Input = styled_components_1.default.input(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  border: #D9D9D9 solid 2px;\n  border-radius: 4px;\n  font-size: 18px;\n  color: #2c2c2c;\n\n  &[type=\"text\"], &[type=\"password\"] {\n    text-align: center;\n    padding: 12px;\n\n    &::placeholder {\n      color: #d0cfcf;\n      text-align: center;\n    }\n  }\n\n  &[type=\"checkbox\"] {\n    label {\n      color: #D9D9D9;\n    }\n  }\n"], ["\n  border: #D9D9D9 solid 2px;\n  border-radius: 4px;\n  font-size: 18px;\n  color: #2c2c2c;\n\n  &[type=\"text\"], &[type=\"password\"] {\n    text-align: center;\n    padding: 12px;\n\n    &::placeholder {\n      color: #d0cfcf;\n      text-align: center;\n    }\n  }\n\n  &[type=\"checkbox\"] {\n    label {\n      color: #D9D9D9;\n    }\n  }\n"])));
exports.Header = styled_components_1.default.h1(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  font-weight: normal;\n"], ["\n  font-weight: normal;\n"])));
exports.SubHeader = styled_components_1.default.h2(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n  font-weight: normal;\n"], ["\n  font-weight: normal;\n"])));
exports.Exit = styled_components_1.default.a(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n  position: absolute;\n  right: 0;\n  cursor: pointer;\n"], ["\n  position: absolute;\n  right: 0;\n  cursor: pointer;\n"])));
exports.CenterContainer = styled_components_1.default.div(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n  ", ";\n"], ["\n  ", ";\n"])), centerStyles);
exports.ImageStyled = (0, styled_components_1.default)(exports.CenterContainer)(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n  margin-left: 8px;\n  cursor: pointer;\n"], ["\n  margin-left: 8px;\n  cursor: pointer;\n"])));
exports.NavStyled = styled_components_1.default.nav(templateObject_14 || (templateObject_14 = __makeTemplateObject(["\n  ", ";\n  margin-top: 22px;\n  position: relative;\n"], ["\n  ", ";\n  margin-top: 22px;\n  position: relative;\n"])), centerStyles);
exports.Column = styled_components_1.default.div(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n  flex-direction: column;\n  display: flex;\n"], ["\n  flex-direction: column;\n  display: flex;\n"])));
exports.RoomsScroll = (0, styled_components_1.default)(exports.Column)(templateObject_16 || (templateObject_16 = __makeTemplateObject(["\n  overflow-y: scroll;\n  height: 100%;\n  width: 100%;\n  align-items: center;\n  padding: 8px;\n"], ["\n  overflow-y: scroll;\n  height: 100%;\n  width: 100%;\n  align-items: center;\n  padding: 8px;\n"])));
exports.Row = styled_components_1.default.div(templateObject_17 || (templateObject_17 = __makeTemplateObject(["\n  display: flex;\n  margin-top: 8px;\n  gap: 8px;\n  width: 100%;\n  justify-content: space-evenly;\n  flex-wrap: wrap;\n"], ["\n  display: flex;\n  margin-top: 8px;\n  gap: 8px;\n  width: 100%;\n  justify-content: space-evenly;\n  flex-wrap: wrap;\n"])));
exports.CenterColumn = (0, styled_components_1.default)(exports.Column)(templateObject_18 || (templateObject_18 = __makeTemplateObject(["\n  ", ";\n"], ["\n  ", ";\n"])), centerStyles);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15, templateObject_16, templateObject_17, templateObject_18;
